#  Template npm-publish

#  This template allows you to publish your npm package, as defined in package.json, to npmjs.com or any other npm-like registry.
#  The workflow allows running tests, code linting and security scans on feature branches (as well as master).
#  The npm package will be validated and published after the code is merged to master.

# Prerequisites: $NPM_TOKEN setup in the Deployment variables.
# For advanced cases, please, follow examples from the pipe's README https://bitbucket.org/atlassian/npm-publish/src/master/README.md

image: node:15.10.0

pipelines:
   branches:
     master:
       - step:
           caches:
             - node
           name: Install
           script:
             - echo "installing modules..."
             - yarn install
             - NODE_ENV=production yarn build
           artifacts:
             - node_modules/**
             - dist/**
       - step:
           name: Deploy to production
           deployment: production
           trigger: manual
           script:
             - scp -r dist/* root@autolib.uz:/root/autolib-front/